import enum


class ErrorType(enum.Enum):
    NONE = 0
    USER_NOT_FOUND = "USER_NOT_FOUND"
    VISIT_ALREADY_EXISTS = "VISIT_ALREADY_EXISTS"
    ACTIVITY_NOT_FOUND = "ACTIVITY_NOT_FOUND"
    VISIT_NOT_FOUND = "VISIT_NOT_FOUND"
    COMPLETEDUSERTASK_ALREADY_EXISTS = "COMPLETEDUSERTASK_ALREADY_EXISTS"

    def __missing__(self, key):
        return self.NONE
